version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
    working_directory: ~/digital-org
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn install
      - run: mvn test
      - run: "bash <(curl -s https://codecov.io/bash)"

#version: 2.1
#jobs:
#  build:
#    machine: true
#    working_directory: ~/repo
#
#    steps:
#      - checkout
#      - run: docker build -t digital-org:CIRCLE_BUILD_NUM .
#workflows:
#  version: 2.1
#  workflow:
#    jobs:
#      - build