version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  codecov: codecov/codecov@1.0.2

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results


description: >
  Upload test results.

  This will populate the Test Summary tab in the CircleCI UI. By default it will

  look in `target/surefire-reports` (the default location for maven test
  results).

  You can override where to find the test results with the path parameter.
parameters:
  test_results_path:
    default: target/surefire-reports
    description: Specify a custom path for maven test results
    type: string
steps:
  - store_test_results:
      path: << parameters.test_results_path >>
  - codecov/upload:
      file: target/surefire-reports

