version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.2

workflows:
  build_and_test:
    jobs:
      - build
      - test # checkout, build, test, and upload test results

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run:
          name: build maven
          command: |
            java -version
            mvn --version
            mvn clean install
      - store_test_results:
          path: target/surefire-reports
