version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.2

workflows:
  build_and_test:
    jobs:
      - checkout
      - build
      - test # checkout, build, test, and upload test results

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - codecov/upload:
          file: target/surefire-reports

