# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.2

workflows:
  build_and_test:
    jobs:
      - checkout
      - build
      - test # checkout, build, test, and upload test results
      - integration-test

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  integration-test:
    executor: orb-tools/codecov
    steps:
      - checkout
      - run:
      - run: mvn clean install
      - codecov/upload:
          file: target/surefire-reports


